### ISSUE TITLE
Field Borders for Cursor

### ISSUE THREAD

**Issue by ErikMayrhofer** [Maxwahl/defunge-editor#2]
# Setup
Cursor is at 0,0
Press `LeftArrow`

# Behaviour
Cursor is at -1, 0

# Expected Behaviour
Cursor should remain at 0, 0 or jump to end of line.

**Comment by Maxwahl** [comment]
fixed in https://github.com/Maxwahl/defunge-editor/commit/d6f7a051f6467dfb24e117743ad14d9b7d700ca9
